name: ai-agent-askus
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - aom=3.6.0
  - appdirs=1.4.4
  - arrow-cpp=19.0.0
  - asgiref=3.8.1
  - asttokens=3.0.0
  - async-timeout=4.0.3
  - attrs=24.3.0
  - automat=24.8.1
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - backoff=1.11.1
  - bcrypt=4.3.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.6.15
  - cachetools=5.5.1
  - cairo=1.16.0
  - certifi=2025.6.15
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - chromadb=1.0.9
  - click=8.1.8
  - coloredlogs=15.0.1
  - comm=0.2.1
  - constantly=23.10.4
  - cpuonly=2.0
  - cryptography=44.0.1
  - cssselect=1.2.0
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - dataclasses-json=0.6.5
  - datasets=3.3.2
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dill=0.3.8
  - distro=1.9.0
  - dnspython=2.4.2
  - durationpy=0.9
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - fastapi=0.115.9
  - fastapi-cli=0.0.7
  - ffmpeg=6.1.1
  - filelock=3.17.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-auth=2.38.0
  - googleapis-common-protos=1.69.2
  - graphite2=1.3.14
  - greenlet=3.1.1
  - grpcio=1.62.2
  - h11=0.14.0
  - harfbuzz=10.2.0
  - html2text=2025.4.15
  - httpcore=1.0.2
  - httptools=0.6.4
  - httpx=0.28.1
  - httpx-sse=0.4.0
  - huggingface_hub=0.31.2
  - humanfriendly=10.0
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.0
  - importlib_resources=6.4.0
  - incremental=24.7.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - itemadapter=0.3.0
  - itemloaders=1.3.2
  - jedi=0.19.2
  - jinja2=3.1.6
  - jiter=0.6.1
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - lame=3.100
  - langchain=0.3.25
  - langchain-chroma=0.2.4
  - langchain-community=0.3.12
  - langchain-core=0.3.60
  - langchain-huggingface=0.2.0
  - langchain-text-splitters=0.3.8
  - langgraph=0.5.0
  - langgraph-checkpoint=2.1.0
  - langgraph-prebuilt=0.5.1
  - langgraph-sdk=0.1.69
  - langsmith=0.1.147
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libnvjitlink=12.4.127
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libpulsar=3.5.1
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzlib=1.2.13
  - lxml=5.3.0
  - lz4-c=1.9.4
  - magma=2.7.1
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - marshmallow=3.19.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mmh3=5.0.1
  - monotonic=1.5
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - mypy_extensions=1.0.0
  - nccl=2.21.5.1
  - ncurses=6.4
  - neo4j-python-driver=5.28.1
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - oauthlib=3.2.2
  - onnxruntime=1.20.1
  - openai=1.59.9
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - opentelemetry-api=1.30.0
  - opentelemetry-exporter-otlp-proto-grpc=1.15.0
  - opentelemetry-instrumentation=0.51b0
  - opentelemetry-instrumentation-asgi=0.51b0
  - opentelemetry-instrumentation-fastapi=0.51b0
  - opentelemetry-proto=1.15.0
  - opentelemetry-sdk=1.30.0
  - opentelemetry-semantic-conventions=0.51b0
  - opentelemetry-util-http=0.51b0
  - orc=2.0.1
  - orjson=3.10.14
  - ormsgpack=1.10.0
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - parsel=1.8.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.1
  - pixman=0.40.0
  - platformdirs=4.3.7
  - posthog=3.16.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - protego=0.4.0
  - protobuf=4.25.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulsar-client=3.5.0
  - pure_eval=0.2.2
  - pyarrow=19.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pydantic-settings=2.6.1
  - pydispatcher=2.0.5
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyopenssl=25.0.0
  - pypika=0.48.9
  - pyproject_hooks=1.0.0
  - pysocks=1.7.1
  - python=3.10.18
  - python-build=1.2.2.post1
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-flatbuffers=24.3.25
  - python-kubernetes=32.0.1
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - queuelib=1.6.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.11.6
  - requests=2.32.3
  - requests-file=1.5.1
  - requests-oauthlib=2.0.0
  - requests-toolbelt=1.0.0
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - rpds-py=0.22.3
  - rsa=4.7.2
  - s2n=1.3.27
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - scrapy=2.12.0
  - sentence-transformers=4.1.0
  - service_identity=18.1.0
  - setuptools=78.1.1
  - shellingham=1.5.0
  - six=1.17.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=2.0.39
  - sqlite=3.45.3
  - stack_data=0.2.0
  - starlette=0.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tenacity=9.0.0
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tldextract=5.1.2
  - tokenizers=0.21.0
  - tomli=2.0.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.49.0
  - twisted=24.11.0
  - typer=0.15.4
  - typer-slim=0.15.4
  - typer-slim-standard=0.15.4
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2025b
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - uvicorn=0.32.1
  - uvicorn-standard=0.32.1
  - uvloop=0.21.0
  - w3lib=2.1.2
  - watchfiles=0.24.0
  - wcwidth=0.2.5
  - websocket-client=1.8.0
  - websockets=10.4
  - wheel=0.45.1
  - wrapt=1.17.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zope=1.0
  - zope.interface=7.1.1
  - zstd=1.5.6
  - pip:
      - langchain-openai==0.3.5
      - langserve==0.3.1
      - sse-starlette==2.3.6
      - tiktoken==0.9.0
prefix: /home/exouser/miniconda3/envs/ai-agent-askus
